### ISSUE TITLE
What's the different between dropdown and select js?

### ISSUE THREAD

**Issue by jenstornell** [zoltantothcom/vanilla-js-dropdown#10]
https://github.com/zoltantothcom/vanilla-js-dropdown/tree/master/dist

There is a `vanilla-js-dropdown.min.js` and a `vanilla-js-select.min.js`. What is the difference? Do I need both or only one of them?

**Comment by zoltantothcom** [comment]
Hi,

You need just `vanilla-js-dropdown.min.js`. The other file is obsolete and left in by mistake - one of the earliest versions of the script. If you take a look at `index.html` you'll see that only one file is referenced - the `dropdown.min` one.

Thanks for finding and pointing this out!
