### ISSUE TITLE
Dropdown won't close after click on option on IE11

### ISSUE THREAD

**Issue by caneta** [zoltantothcom/vanilla-js-dropdown#12]
Hi, great plugin!
But I noticed that it has a bug in IE11: the dropdown won't close after click on an option!
Is that possible to fix?

**Comment by usame-algan** [comment]
Hey @caneta,
you need to include a Polyfill for [CustomEvent](https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/CustomEvent#Polyfill) in order for it to work in IE11.
