### ISSUE TITLE
Optgroup

### ISSUE THREAD

**Issue by grobmeier** [zoltantothcom/vanilla-js-dropdown#13]
Unfortunately optgroups are not supported :-(

**Comment by zoltantothcom** [comment]
Thank you for pointing this out 👍Fixed 🎉 
Please check out the [**Demo**](http://zoltantothcom.github.io/vanilla-js-dropdown/) section.

**Comment by grobmeier** [comment]
Awesome. Thanks for improving it so quickly, I am positively surprised!
