### ISSUE TITLE
Support For Disabled Options

### ISSUE THREAD

**Issue by sprankhub** [zoltantothcom/vanilla-js-dropdown#28]
I know you want to keep this as small as possible (and I like that!). However, I think there should at least be support for disabled options. Currently, if an option is disabled, it can still be selected via the respective HTML elements. I would expect two changes:

1. HTML elements of disabled options should get a `is-disabled` CSS class.
2. Clicks on the HTML elements of disabled options should be ignored.

**Comment by sprankhub** [comment]
Before I put more work into that... Would you be willing to merge such a change, @zoltantothcom?

**Comment by sprankhub** [comment]
Mind commenting on that, @zoltantothcom? I do not expect you to implement it, "just" to say yes, to review and eventually to merge :-)

**Comment by sprankhub** [comment]
Could you please give me feedback here, @zoltantothcom?

**Comment by zoltantothcom** [comment]
@sprankhub Sorry, my man, for this extremely late reply 🙏 I finally got to review my repos and want to thank you for your idea, contribution and time. Right after I'll update the tests I will absolutely merge this feature. Thank you and sorry once again.
