### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by ghost** [zoltantothcom/vanilla-js-dropdown#59]
Hi everyone.

I want to help, but I want to know if this project is active. *Is this project active?*

**Comment by zoltantothcom** [comment]
@codehangen  It's _somewhat_ active :) If there is a really cool feature you have in mind - I will definitely consider adding it.

**Comment by ghost** [comment]
Hi zoltantothcom.

> @codehangen It's somewhat active :) If there is a really cool feature you have in mind - I will definitely consider adding it.

thank you for feedback. So I would like to contribute to this repository.

**Comment by zoltantothcom** [comment]
Sure thing! You're more than welcome. Do you mind me to ask what exactly you have in mind?

**Comment by ghost** [comment]
Hi zoltantothcom.

> Sure thing! You're more than welcome. Do you mind me to ask what exactly you have in mind?

I would like to translate the site vanilla-js-dropdow from en-us to pt-br.
