### ISSUE TITLE
Use 'hasAttribute' to be more forgiving

### ISSUE THREAD

**Issue by cho-leukeleu** [zoltantothcom/vanilla-js-dropdown#6]
Currently having set `selected="selected"` as attribute will result in `getAttribute('selected')` returning `null` (eventhough `selectOptions[i].selected` returns `true`)

https://github.com/zoltantothcom/vanilla-js-dropdown/blob/4226b311ed4536779f8b3536c9350c46c30b3fa8/src/javascript/vanilla-js-dropdown.js#L48

**Comment by zoltantothcom** [comment]
Can you please clarify what's not working? 
Cant seem to reproduce the issue in this [JSBin example](https://jsbin.com/yaxusofoki/edit?html,js,console,output)

**Comment by cho-leukeleu** [comment]
Hi @zoltantothcom 
Here is a pastebin with what I meant: https://jsbin.com/sawihohoda/edit?html,js,console,output

**Comment by zoltantothcom** [comment]
I really like when issues and bugs magically fix themselves 😄
