### ISSUE TITLE
Update NPM version

### ISSUE THREAD

**Issue by FreekVR** [zoltantothcom/vanilla-js-dropdown#9]
Hey there!

I'm running into this issue: https://github.com/zoltantothcom/vanilla-js-dropdown/issues/5

This already appears to be fixed in 2.1.1, but I'm including the code using NPM and that seems to still be on 2.1.0. Would it be possible to update the NPM version to 2.1.1 as well?

Thanks!

**Comment by zoltantothcom** [comment]
Sorry for the delay. Updated.
